services:
  - type: web
    name: ivanseg-frontend
    runtime: node
    repo: https://github.com/Leviathan-19/Ivanseg-Extintores
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    publishDir: dist/src